// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsX7q1zR6BbHdD2R_D-p_4RTAgHYdi_wU',
    appId: '1:223084538450:web:d9f5e14303d30edc148d8b',
    messagingSenderId: '223084538450',
    projectId: 'travel-checklist-55f65',
    authDomain: 'travel-checklist-55f65.firebaseapp.com',
    storageBucket: 'travel-checklist-55f65.appspot.com',
    measurementId: 'G-5KV38QHCWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcgybcAoEu_sSp8krQRZWwupqD0s27nGw',
    appId: '1:223084538450:android:bef88dd664e5085b148d8b',
    messagingSenderId: '223084538450',
    projectId: 'travel-checklist-55f65',
    storageBucket: 'travel-checklist-55f65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL3hHVDBCo0cOOBmyxWjZAY9SfwF3ti-U',
    appId: '1:223084538450:ios:b87e7f721b50a190148d8b',
    messagingSenderId: '223084538450',
    projectId: 'travel-checklist-55f65',
    storageBucket: 'travel-checklist-55f65.appspot.com',
    iosClientId: '223084538450-jict5f7gd3n6staft207l5v21btraufo.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelChecklist',
  );
}
